@startuml Deployment Diagram

!define TraefikNode component
!define ServiceNode component

node "Docker Host" {
    TraefikNode Traefik
    ServiceNode Whoami
    ServiceNode OpenLDAP
    ServiceNode LdapAccountManager
    ServiceNode Kanidm
    ServiceNode Gitlab
    node "Nextcloud Stack" {
        ServiceNode Nextcloud
        ServiceNode NextcloudDB
        ServiceNode NextcloudRedis
    }
    ServiceNode Vaultwarden
    ServiceNode VPN
    ServiceNode Portainer
    node "AISIX AI Gateway Stack" {
        ServiceNode Aisix
        ServiceNode Etcd
    }

    Traefik -down-> Whoami : routes
    Traefik -down-> Kanidm : routes
    Traefik -down-> Gitlab : routes
    Traefik -down-> Nextcloud : routes
    Traefik -down-> Vaultwarden : routes
    Traefik -down-> Aisix : routes (aisix.*, aisix-admin.*)

    Gitlab -left-> OpenLDAP : auth
    Nextcloud -right-> OpenLDAP : auth
    LdapAccountManager -up-> OpenLDAP : manage

    Nextcloud -down-> NextcloudDB : db
    Nextcloud -down-> NextcloudRedis : cache

    Aisix -down-> Etcd : config store
}

@enduml
